trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo FirstJob Build
  - job: SecondJob
    steps:
    - bash: echo SecondJob Build

- stage: DevDeploy
  jobs:
  - job: FirstJob
    steps:
    - bash: echo FirstJob DevDeploy
- stage: QADeploy
  jobs:
  - job: FirstJob
    steps:
    - bash: echo FirstJob QADeploy
- stage: ProdDeploy
  jobs:
  - job: FirstJob
    steps:
    - bash: echo FirstJob ProdDeploy

