trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo FirstJob Build
    - bash: echo $(pipelinelevelvariable)
  - job: SecondJob
    steps:
    - bash: echo SecondJob Build
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Buld.SourceDirectory)
    - bash: echo $(Build.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: java -version
    - bash: python --version
    - bash: node --version
    - bash: mvn -version
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

# - stage: DevDeploy
#   variables:
#    environment: Dev
#   dependsOn: Build
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo FirstJob DevDeploy
#     - bash: echo environment $(environment)
# - stage: QADeploy
#   variables:
#    environment: QA
#   dependsOn: Build
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo FirstJob QADeploy
#     - bash: echo environment $(environment)
# - stage: ProdDeploy
#   variables:
#     environment: Prod
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo FirstJob ProdDeploy
#     - bash: echo environment $(environment)

