trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
  
# strategy:
#  matrix:
#    linux:
#      operatingSystem: 'ubuntu-latest'
#    mac:
#     operatingSystem: 'macos-15'

stages:
- stage: Build
  jobs:
    - job: BuildJob
      steps:
      - script: echo "do this build"

- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploy to Dev

- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Deploy to QA

# steps:
# - script: echo $(operatingSystem)
#   displayName: 'Run a one-line script'

