trigger:
- main

strategy:
 matrix:
   linux:
     operatingSystem: 'ubuntu-latest'
   mac:
    operatingSystem: 'macos-15'

pool:
  vmImage: $(operatingSystem)

steps:
- script: echo $(operatingSystem)
  displayName: 'Run a one-line script'

