trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Kubernates Azure DevOps Pipeline IAAC
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret)'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    backendAzureRmTenantId: '96f6082f-bc39-42e6-a8b9-54590a3ca46a'
    backendAzureRmSubscriptionId: '96f6082f-bc39-42e6-a8b9-54590a3ca46a'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageacctmunixyz'
    backendAzureRmContainerName: 'storageacctmunicontainer'
    backendAzureRmKey: 'kubernates-dev.tfstate'
    allowTelemetryCollection: false